### PR TITLE
Sync Jade into Kinetic

### PR DESCRIPTION
**Pull request by davetcoleman**
Simply the latest jade-devel rebased into the currently unused and way out of date kinetic branch

Per https://github.com/ros-planning/moveit_ros/issues/695

### CODE REVIEW

**Comment by davetcoleman** [comment]
@130s can you take a look at why the industrial_ci Travis script is failing for Kinetic? It isn't showing any error information...

**Comment by davetcoleman** [comment]
@130s I don't understand why industrial_ci isn't pulling my specified rosinstall file, I'm using this format:

> - ROS_DISTRO="kinetic"  ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu UPSTREAM_WORKSPACE=file  ROSINSTALL_FILENAME=https://raw.githubusercontent.com/ros-planning/moveit_docs/kinetic-devel/moveit.rosinstall

Travis keeps failing saying moveit_msgs is missing...

**Comment by davetcoleman** [comment]
Found bug in industrial_ci script: https://github.com/ros-industrial/industrial_ci/pull/70

**Comment by davetcoleman** [comment]
It took me a couple days but I finally got a Travis file that builds correctly for kinetic. It's a fork of industrial_ci but it a) doesn't time out b) doesn't have too much log out put and c) uses OSRF's ROS docker to run Ubuntu 16.04. I think this is ready to merge

**Comment by davetcoleman** [comment]
Ping - this is ready to merge.
Note: includes new CI script https://github.com/ros-planning/moveit_core/issues/309

**Comment by rhaschke** [comment]
+1

**Pull request merged**
