### PR TITLE
Improved error output for state conversion

### PR DESCRIPTION
**Pull request by davetcoleman**
Fixed silent error when converting a `moveit_msgs::RobotState` message to a `RobotState` object. Other failures in robot_state/conversions have failure messages, so this should too.

### CODE REVIEW

**Comment by sachinchitta** [comment]
Aah, this PR is a regression - did not realize that earlier - it will have to be pulled back. Looks like the meaning of "missing" values is being misinterpreted here since the incoming const state message can always have missing values (which is what is being checked for). 

@isucan - could you check and please confirm that I am correct.

**Comment by isucan** [comment]
You are correct Sachin. The error message is incorrect and we need to pull this one back.

**Comment by davetcoleman** [comment]
I apologize for the regression, though I still don't fully understand... the header for `robotStateMsgToRobotState` says it returns false if it "failed for any reason", so the error message I added informs the user why it failed. 

I believe you are saying that it is ok to fail and we should not have an error message? I think the header doxygen should then be reworded to say something like "returns false if not all frames of the robot state are provided" and then take out my error message. That is to say, define the return state as not being a failure.

**Comment by sachinchitta** [comment]
Its fine - I think there was a bug the way it was setup originally anyways - I pushed a new PR that should fix this #152.

**Comment by davetcoleman** [comment]
Ah, so now it doesn't care about missing links, that was a bug indeed.

**Pull request merged**
