### PR TITLE
adding angles dependency

### PR DESCRIPTION
**Pull request by sachinchitta**

### CODE REVIEW

**Comment by davetcoleman** [comment]
I assume this is for https://github.com/ros-planning/moveit_core/issues/181

**Comment by dirk-thomas** [comment]
You can not `find_package(angles)` in the not-testing part of the CMakeLists file when you don't depend on the package. This will not work.

**Comment by davetcoleman** [comment]
Good point. What is the correct way to include the package in CMakeLists for testing then?

**Comment by dirk-thomas** [comment]
You `<test_depend>` on the package, call `find_package(NAME)` within you `CATKIN_TESTING_ENABLED` block and also in there use include dirs, libraries etc.

**Pull request merged**
