### PR TITLE
fixes #113 #114 and #115 failing test by adding myriad calls to update the robot state afte...

### LINKED ISSUE #113: Test Broken: kinematic_constraints PositionConstraintsMobile
/home/schitta/code/moveit/src/moveit_core/kinematic_constraints/test/test_constraints.cpp:486: Failure
Value of: pc.decide(ks).satisfied
  Actual: false
Expected: true
/home/schitta/code/moveit/src/moveit_core/kinematic_constraints/test/test_constraints.cpp:498: Failure
Value of: pc.decide(ks).satisfied
  Actual: false
Expected: true
/home/schitta/code/moveit/src/moveit_core/kinematic_constraints/test/test_constraints.cpp:522: Failure
Value of: pc.decide(ks, false).satisfied
  Actual: false
Expected: true
[  FAILED  ] LoadPlanningModelsPr2.PositionConstraintsMobile (619 ms)

### PR DESCRIPTION
**Pull request by jon-weisz**
...r modifying it.

### CODE REVIEW

**Comment by jon-weisz** [comment]
@sachinchitta -  I'm not sure this is the right way to fix this issue - I'm not that familiar with the API, but I don't see any way to automatically update the dirty transforms, and the tests seems to expect them to be up to date before running their assertions.

**Comment by jon-weisz** [comment]
@davetcoleman - Travis is recorded an error with this PR. Should the indigo-devel branch be getting built on precise?

**Comment by mikeferguson** [comment]
@jon-weisz Nothing indigo-based works right with Travis right now -- as they only support Precise and so all the indigo debs are missing.

**Comment by davetcoleman** [comment]
Side note: I think we should just disable travis in the indigo branch.

**Comment by davetcoleman** [comment]
+1 this makes sense to me but I'd like to get @isucan 's take on the proper use of `update()`

**Comment by jon-weisz** [comment]
seems like @sachinchitta and @isucan  might be busy. Perhaps @mpomarlan might know? It would be nice to get the tests passing.

**Comment by isucan** [comment]
This looks good!

**Comment by davetcoleman** [comment]
Great!

**Pull request merged**
