### PR TITLE
kinematics_base: added an optional RobotState for context.

### PR DESCRIPTION
**Pull request by hersh**
For my humanoid work, I need a way for the IK solver to know the position values of all joints, not just the ones in the group.

### CODE REVIEW

**Comment by hersh** [comment]
@sachinchitta can you take a look at this?

**Comment by sachinchitta** [comment]
+1 LGTM.

**Comment by isucan** [comment]
+1

**Comment by hersh** [comment]
woot

**Comment by davetcoleman** [comment]
Super awesome

**Pull request merged**
