### PR TITLE
Added maximum acceleration scaling factor

### PR DESCRIPTION
**Pull request by ghost**
This is a change related to ros-planning/moveit_ros#634 and adds a maximum acceleration scaling factor for optionally limiting trajectory acceleration.

### CODE REVIEW

**Comment by davetcoleman** [comment]
+1 lgtm

could you look into why there is a merge conflict?

**Comment by ghost** [comment]
Yeah, I don't really know what the issue is.  I am fairly new to Git and assumed someone would enlighten me....

**Comment by davetcoleman** [comment]
there are many ways to fix this

make sure you have two remotes added to your .git/config file - github.com/hemes and github.com/ros-planning. then you can create a branch that tracks the upstream version

```
git checkout -b upstream-indigo-devel upstream/indigo-devel
```

switch back to your branch

```
git checkout indigo-devel
```

now merge

```
git merge upstream-indigo-devel
```

to see conflicts

```
git diff
```

commit after resolving the conflicts

**Comment by ghost** [comment]
Nice. That took me longer than it should have but I finally got it.  The issue was with your most recent whitespace changes. Should be good now; thanks for your help!

**Comment by davetcoleman** [comment]
FYI I'm waiting on a +1 from someone else before merging this, since it changes a ROS message in Indigo

**Comment by dornhege** [comment]
In principle this looks good to me, but I can't see a message being changed. There is only one parameter added to the public API, including a default value. Unless we'd want to guarantee ABI compatibility this should be fine.

However, the second merge commit looks odd to me as it contains a lot of (whitespace) changes that aren't visible in the "files changed" tab.

**Comment by davetcoleman** [comment]
This message is being changed:
https://github.com/ros-planning/moveit_msgs/pull/17/files

**Comment by ghost** [comment]
@dornhege Git newcomer here but I believe the commit strangeness is from me updating my fork to include #271, which happened after I forked it initially (and was causing a merge conflict).  Maybe I merged incorrectly somehow?

**Comment by dornhege** [comment]
@davetcoleman I didn't see the dependent pull request. For this one it's a +1 for me also in connection with the message.

@hemes I believe that's from the whitespace changes, so your changes should apply cleanly. It probably only shows because it's a bit forth and back. You could try to remove the merge commit and instead `git rebase upstream/indigo-devel`. I would recommend to backup your repository before you do.

**Comment by ghost** [comment]
@dornhege All right, I think I got it fixed up.

**Pull request merged**
