### PR TITLE
avoid unnecessary calculations

### PR DESCRIPTION
**Pull request by acornacorn**
If we are not going to use the "missing" vector then we should not create it
(avoid an expensive operation).

This is related to the changes in https://github.com/ros-planning/moveit_core/pull/152 and https://github.com/ros-planning/moveit_core/pull/148

### CODE REVIEW

**Comment by isucan** [comment]
+1

**Comment by davetcoleman** [comment]
+1 good call

**Comment by davetcoleman** [comment]
Concerning the newly defined PR policy - I thoroughly read through the changes in this PR and am experienced with it since I made related changes to it very recently, Ioan also +1, so it is ok that I merged. Correct?

**Comment by isucan** [comment]
If you are confident and understand the changes you merge,  it is fine to merge. The way I like to think about it is that you share responsibility with the submitter in fixing the problem if you merge something bad.

**Pull request merged**
