### PR TITLE
Kinematic base updates

### PR DESCRIPTION
**Pull request by jrgnicho**
Reinstated the PR for extending the KinematicsBase interface as described in this PR #231 
@sachinchitta please review.

### CODE REVIEW

**Comment by davetcoleman** [comment]
Is this the same PR that has already been merged into the `jade-devel` branch?

**Comment by jrgnicho** [comment]
@davetcoleman , yes but I had to recreate it since I had deleted the fork from which the PR had been originated.

**Comment by davetcoleman** [comment]
It looks good, but I can't exactly remember - did we agree to also add these changes back into indigo?

**Comment by jrgnicho** [comment]
Yes, I believe so.  In fact I remember being tasked with verifying that the changes didn't break any old (indigo) ikfast implementations.

**Pull request merged**
