### PR TITLE
need angles dependency for tests

### PR DESCRIPTION
**Pull request by sachinchitta**

### CODE REVIEW

**Comment by isucan** [comment]
This is a test depend, so it should be defined as such in package.xml - not run/ build depend

**Comment by sachinchitta** [comment]
Yup, you are right - done. Will do a new release of moveit_core tomorrow if this passes Travis.

**Comment by acornacorn** [comment]
Travis failed because angles is a test-only depend but is exported as a dependent package dependency.  I think you need to remove angles from the catkin_package macro and add it as a standalone find_package (without REQUIRED).

**Comment by hersh** [comment]
@sachinchitta, have you compiled this?  For some reason Travis didn't build from your more recent changes, so the latest build result I see is a failure.

**Comment by sachinchitta** [comment]
Yes, I did compile it. I am not sure why Travis did not rebuild.

**Pull request merged**
