### PR TITLE
catkin_lint cleanup jade-devel

### PR DESCRIPTION
**Pull request by v4hn**
This is basically #305 for jade.

### CODE REVIEW

**Comment by davetcoleman** [comment]
why is travis not running?

**Comment by v4hn** [comment]
No idea, it works for #318 . Any idea how to trigger it?

**Comment by d130s** [comment]
It can happen between Travis and Github. Close the pr and reopen it might
work (I can't for now from my phone).

**Comment by davetcoleman** [comment]
It doesn't appear on Travis... maybe it is to similar to #318 so it filtered it out? Attempting to reopen.

**Comment by davetcoleman** [comment]
Travis: Could not find a package configuration file provided by "Eigen3"

**Comment by v4hn** [comment]
okok, I yield :p .
I thought `find_package(Eigen3)` should be fine in jade,
but this still hits this weird problem that catkin tools can't find Eigen3 although `FindEigen3.cmake` is around in ubuntu 14.04..
Anyway, I updated the request.

**Pull request merged**
