### PR TITLE
Added running of currently passing tests to .travis.yml.

### PR DESCRIPTION
**Pull request by hersh**

### CODE REVIEW

**Comment by hersh** [comment]
The change to CMakeLists.txt adding find_package(orocos_kdl) seemed necessary to get the tests to build for me.

**Comment by isucan** [comment]
I think the change to CMakeLists.txt is fine.

**Comment by hersh** [comment]
Ooops, I should have commented on this before.  The travis runs of these tests are actually NOT passing.  For some reason the Travis result stuff wasn't showing up on this pull request page.

I'll fix the test or remove it from the .travis.yml file in a separate pull request.

**Comment by hersh** [comment]
New pull request submitted should fix the problem.

**Pull request merged**
