### PR TITLE
[jade] Update Travis conf for Ubuntu Trusty.

### PR DESCRIPTION
**Pull request by 130s**
Could any admins enable Travis at https://travis-ci.org/profile/ros-planning/ (can be done with a single click) and poke me? Thanks in advance.

(I assume the reason why Travis is disabled is the same as https://github.com/ros-planning/moveit_commander/pull/44#issuecomment-213208068).

### CODE REVIEW

**Comment by davetcoleman** [comment]
poke

**Comment by 130s** [comment]
@jacquelinekay @wjwwood Could any of you help us again?
And `moveit_ros` repository too if possible. Just one click more ;)

**Comment by davetcoleman** [comment]
@130s I've been looking at this new .travis.yml file further and have some questions:
- Can we move all the `if [[ ${PRERELEASE} == true ]];` scripts to a separate bash script in the repo to simplify reading? e.g. `.rosPreRelease.sh` ?
- Or could we integrate the pre-release stuff into industrial_ci, where it belongs IMHO?
- Why does this travis file looks so different than the one documented on industrial_ci? e.g. the allowed_failures matrix and env matrix?

**Comment by davetcoleman** [comment]
@130s now that ros-industrial/industrial_ci#35 is merged should we update this to not include the duplicate pre-release functionality?

**Comment by 130s** [comment]
@davetcoleman ya, #292 is it ;)

**Comment by davetcoleman** [comment]
oops haven't gotten through all my emails

**Pull request merged**
