### PR TITLE
Use libfcl-dev rosdep key in kinetic

### LINKED ISSUE #280: Potential for change in fcl package name
There is some discussion about using the upstream version of the fcl package in ROS K instead of the ROS version (see https://github.com/ros-gbp/fcl-release/issues/1 ). If we change this, then a `kinetic-devel` branch will need to be created so the `package.xml` can be modified with the new name.

### PR DESCRIPTION
**Pull request by scpeters**
Closes #280.

### CODE REVIEW

**Comment by scpeters** [comment]
Since travis doesn't support Xenial, we disabled travis on the `kinetic-devel` branch of gazebo_ros_pkgs ( https://github.com/ros-simulation/gazebo_ros_pkgs/pull/431 ) and enabled the new ROS buildfarm in its place. I'll ask @wjwwood how to set up the buildfarm for this repo.

**Comment by wjwwood** [comment]
http://wiki.ros.org/buildfarm/Pull%20request%20testing

**Comment by davetcoleman** [comment]
Has `ros-planning` org been granted access to the user `ros-pull-request-builder`?  "in order to allow Jenkins to setup the necessary web hooks."

I just added the flag to the distro in jade

**Comment by scpeters** [comment]
That was just to `jade/distribution.yaml`; maybe it needs another PR for `kinetic/distribution.yaml`?

**Comment by davetcoleman** [comment]
good point. but moveit has not been released into kinetic yet...

but im also just curious if we should replace all our travis usage with ROS buildfarm, since our travis coverage has never really been fixed since hydro when it didn't support 14.04 for a long time

**Comment by davetcoleman** [comment]
went ahead and merged this into kinetic branch for future use

**Comment by davetcoleman** [comment]
@wjwwood will this automatically add a web hook to github? can i get a badge indicating its status?

**Comment by wjwwood** [comment]
Yes, so long as the @ros-pull-request-builder user has admin access on the repository. 

There are badges if you go to the pr job for your repository on the build farm. There is an "embedable build status badge" link on the left side that gives you instructions on how to use them.

**Pull request merged**
